"""Static license classification data."""

LICENSE_DATA: dict[str, dict[str, str]] = {
    # Permissive licenses
    "MIT": {"category": "permissive", "name": "MIT License"},
    "APACHE-2.0": {"category": "permissive", "name": "Apache License 2.0"},
    "BSD-2-CLAUSE": {"category": "permissive", "name": "BSD 2-Clause License"},
    "BSD-3-CLAUSE": {"category": "permissive", "name": "BSD 3-Clause License"},
    "ISC": {"category": "permissive", "name": "ISC License"},
    "0BSD": {"category": "permissive", "name": "BSD Zero Clause License"},
    "UNLICENSE": {"category": "permissive", "name": "The Unlicense"},
    "CC0-1.0": {"category": "permissive", "name": "Creative Commons Zero v1.0 Universal"},
    "ZLIB": {"category": "permissive", "name": "zlib License"},
    "WTFPL": {"category": "permissive", "name": "Do What The F*ck You Want To Public License"},
    "PYTHON-2.0": {"category": "permissive", "name": "Python License 2.0"},
    "PSF-2.0": {"category": "permissive", "name": "Python Software Foundation License 2.0"},
    "ARTISTIC-2.0": {"category": "permissive", "name": "Artistic License 2.0"},
    # Copyleft licenses
    "GPL-2.0": {"category": "copyleft", "name": "GNU General Public License v2.0"},
    "GPL-2.0-ONLY": {"category": "copyleft", "name": "GNU General Public License v2.0 only"},
    "GPL-2.0-OR-LATER": {"category": "copyleft", "name": "GNU General Public License v2.0 or later"},
    "GPL-3.0": {"category": "copyleft", "name": "GNU General Public License v3.0"},
    "GPL-3.0-ONLY": {"category": "copyleft", "name": "GNU General Public License v3.0 only"},
    "GPL-3.0-OR-LATER": {"category": "copyleft", "name": "GNU General Public License v3.0 or later"},
    "LGPL-2.0": {"category": "copyleft", "name": "GNU Lesser General Public License v2.0"},
    "LGPL-2.1": {"category": "copyleft", "name": "GNU Lesser General Public License v2.1"},
    "LGPL-2.1-ONLY": {"category": "copyleft", "name": "GNU Lesser General Public License v2.1 only"},
    "LGPL-2.1-OR-LATER": {"category": "copyleft", "name": "GNU Lesser General Public License v2.1 or later"},
    "LGPL-3.0": {"category": "copyleft", "name": "GNU Lesser General Public License v3.0"},
    "LGPL-3.0-ONLY": {"category": "copyleft", "name": "GNU Lesser General Public License v3.0 only"},
    "LGPL-3.0-OR-LATER": {"category": "copyleft", "name": "GNU Lesser General Public License v3.0 or later"},
    "AGPL-3.0": {"category": "copyleft", "name": "GNU Affero General Public License v3.0"},
    "AGPL-3.0-ONLY": {"category": "copyleft", "name": "GNU Affero General Public License v3.0 only"},
    "AGPL-3.0-OR-LATER": {"category": "copyleft", "name": "GNU Affero General Public License v3.0 or later"},
    "MPL-2.0": {"category": "copyleft", "name": "Mozilla Public License 2.0"},
    "EUPL-1.2": {"category": "copyleft", "name": "European Union Public License 1.2"},
    "SSPL-1.0": {"category": "copyleft", "name": "Server Side Public License 1.0"},
    "CDDL-1.0": {"category": "copyleft", "name": "Common Development and Distribution License 1.0"},
    "EPL-1.0": {"category": "copyleft", "name": "Eclipse Public License 1.0"},
    "EPL-2.0": {"category": "copyleft", "name": "Eclipse Public License 2.0"},
}

SPDX_ALIASES: dict[str, str] = {
    # Apache variants
    "Apache 2.0": "APACHE-2.0",
    "Apache-2.0": "APACHE-2.0",
    "Apache 2": "APACHE-2.0",
    "Apache License 2.0": "APACHE-2.0",
    "Apache License, Version 2.0": "APACHE-2.0",
    "apache2": "APACHE-2.0",
    "apache-2": "APACHE-2.0",
    # MIT variants
    "mit": "MIT",
    "The MIT License": "MIT",
    "MIT License": "MIT",
    # BSD variants
    "BSD": "BSD-3-CLAUSE",
    "BSD License": "BSD-3-CLAUSE",
    "BSD-3-Clause": "BSD-3-CLAUSE",
    "BSD-2-Clause": "BSD-2-CLAUSE",
    "Simplified BSD": "BSD-2-CLAUSE",
    "New BSD": "BSD-3-CLAUSE",
    "Modified BSD": "BSD-3-CLAUSE",
    # ISC
    "isc": "ISC",
    "ISC License": "ISC",
    # GPL variants
    "GPL": "GPL-3.0",
    "GPLv2": "GPL-2.0",
    "GPLv3": "GPL-3.0",
    "GPL-2": "GPL-2.0",
    "GPL-3": "GPL-3.0",
    "GNU GPL": "GPL-3.0",
    "GNU GPLv2": "GPL-2.0",
    "GNU GPLv3": "GPL-3.0",
    "GNU General Public License v2": "GPL-2.0",
    "GNU General Public License v3": "GPL-3.0",
    # LGPL variants
    "LGPL": "LGPL-2.1",
    "LGPLv2": "LGPL-2.0",
    "LGPLv2.1": "LGPL-2.1",
    "LGPLv3": "LGPL-3.0",
    "LGPL-2": "LGPL-2.0",
    "LGPL-3": "LGPL-3.0",
    "GNU Lesser General Public License v2": "LGPL-2.0",
    "GNU Lesser General Public License v2.1": "LGPL-2.1",
    "GNU Lesser General Public License v3": "LGPL-3.0",
    # AGPL variants
    "AGPL": "AGPL-3.0",
    "AGPLv3": "AGPL-3.0",
    "AGPL-3": "AGPL-3.0",
    "GNU Affero General Public License v3": "AGPL-3.0",
    # MPL
    "MPL": "MPL-2.0",
    "MPL2": "MPL-2.0",
    "Mozilla Public License 2.0": "MPL-2.0",
    # Others
    "CC0": "CC0-1.0",
    "Public Domain": "UNLICENSE",
    "Unlicense": "UNLICENSE",
    "Python": "PYTHON-2.0",
    "PSF": "PSF-2.0",
    "WTFPL": "WTFPL",
    "zlib": "ZLIB",
    "Zlib": "ZLIB",
}
